---
home: https://github.com/explorium-ai/kube-auto-puller
keywords:
  - kube-fledged
  - image
  - kubernetes
  - cache
  - pull
sources:
  - https://github.com/explorium-ai/kube-auto-puller
annotations:
  category: Kubernetes
apiVersion: v2
appVersion: "1.0"
description: A Kubernetes Image Puller and Cacher with Automatic Discovery
maintainers:
  - email: devops@explorium.ai
    name: explorium-ai
    url: https://www.explorium.ai/
dependencies:
  - name: kube-fledged
    repository: https://senthilrch.github.io/kubefledged-charts/
    version: v0.10.0
  - name: webhook-receiver
    version: 1.0.9
  - name: ecr-creds
    version: 0.0.1
    condition: ecr-creds.enabled
name: kube-auto-puller
version: 1.0.0
