---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{include "webhook-receiver.serviceAccountName" .}}
  labels:
    {{- include "webhook-receiver.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "webhook-receiver.serviceAccountName" . }}
rules:
  - apiGroups: ["kubefledged.io"]
    resources: ["imagecaches"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]    
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "webhook-receiver.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "webhook-receiver.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "webhook-receiver.serviceAccountName" . }}
    namespace: {{.Release.Namespace}}
